[versions]
ktor = "3.2.3"
logback = "1.5.18"
logstash = "8.1"
junit-jupiter = "5.13.4"

[libraries]
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-jupiter" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logstash = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash" }

[bundles]
ktor = [
    "ktor-server-core",
    "ktor-server-netty",
]
logging = [
    "logback",
    "logstash"
]