name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  workflow_run:
    workflows: ['Dependabot auto-merge']
    types: [completed]
jobs:
  test-build-deploy:
    permissions:
      contents: write # for dependency graph & sarif
      security-events: write # push sarif to github security
      id-token: write # for nais docker-build-push
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b
        with:
          java-version: 21
          distribution: temurin
      - uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6
      - name: Test & build
        run: ./gradlew test build
      - name: Build & push docker image + SBOM
        uses: nais/docker-build-push@5246e4705d79945a0ec28eb9bd3638dd534fee46
        id: docker-push
        with:
          team: appsec
          pull: true
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@0bdd871935719febd78681f197cd39af5b6e16a6
      - name: Scan docker image for secrets
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0
        with:
          image-ref: '${{ steps.docker-push.outputs.image }}'
          format: 'sarif'
          scanners: 'secret'
          output: 'trivy.sarif'
      - uses: github/codeql-action/upload-sarif@17a820bf2e43b47be2c72b39cc905417bc1ab6d0
        with:
          sarif_file: 'trivy.sarif'
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: read
    needs: test-build-deploy
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      #- uses: nais/deploy/actions/deploy@7c152a10f4da3ca352d57a25eba0b3a8e04882f9
      #  env:
      #    RESOURCE: .nais/nais.yaml
      #    CLUSTER: prod-gcp
      #    IMAGE: ${{ steps.docker-push.outputs.image }}
