name: Trivy dockerimage scan
on:
  repository_dispatch:
    types: [start-trivy]
  schedule:
    - cron: '32 13 * * 1'
jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write # to write sarif
      security-events: write # push sarif to github security
      id-token: write # for nais/login
    steps:
      - uses: nais/login@4ce7445c84f09114e481a1d2c164f563e9e2ba8e
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: appsec
      - uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0
        env:
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db
        with:
          image-ref: '${{ github.event.client_payload.image }}'
          format: 'sarif'
          output: 'trivy.sarif'
      - uses: github/codeql-action/upload-sarif@b6a472f63d85b9c78a3ac5e89422239fc15e9b3c
        with:
          sarif_file: 'trivy.sarif'
